/*
* Copyright 2015 Seven Spikes Ltd. All rights reserved. (http://www.nop-templates.com)
* http://www.nop-templates.com/t/licensinginfo
*/

var breakPointWidth=980,megaMenuSkipEventBinding=!1,appSettings;(function(){"function"!==typeof String.prototype.trim&&(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});"function"!==typeof String.prototype.startsWith&&(String.prototype.startsWith=function(a){return 0==this.indexOf(a)})})();var errorsCounter=0;
window.onerror=function(a,b,c){null==document.body||10<errorsCounter||(a="URL: "+b+"\u00a7\u00a7MESSAGE: "+a+"\u00a7\u00a7ROW: "+c,b=document.createElement("input"),b.setAttribute("class","javascriptErrorsElement"),b.setAttribute("type","hidden"),b.setAttribute("value",a),document.body.appendChild(b),errorsCounter++)};
window.onload=function(){$(".block").each(function(){$.getSpikesViewPort().width<=breakPointWidth&&$(this).find(".jcarousel-container-vertical").hide()});if($.isMobile())$(".mega-menu-responsive .labelForNextPlusButton").on("click",function(){$(this).next(".plus-button").click()})};
function initResponsiveTheme(a,b){appSettings=null===b||"undefined"===typeof b?{isEnabled:!1}:b;void 0!=appSettings.selectors&&(null==appSettings.selectors.headerLinksWrapperMobileInsertAfter&&(appSettings.selectors.headerLinksWrapperMobileInsertAfter=".header"),null==appSettings.selectors.headerLinksWrapperDesktopPrependTo&&(appSettings.selectors.headerLinksWrapperDesktopPrependTo=".header"));breakPointWidth=a.themeBreakpoint;var c=!1;"true"==$("#isRtlEnabled").val()&&(c=!0);var e=$.getSpikesViewPort().width,
d=function(b){var d=$.getSpikesViewPort().width;appSettings.isEnabled&&b&&appSettings.doesDesktopHeaderMenuStick&&$(appSettings.selectors.headerMenu).wrap('<div id="headerMenuParent"></div>');if(b||d>breakPointWidth&&e<=breakPointWidth||d<=breakPointWidth&&e>breakPointWidth){var f=".plus-button";appSettings.isEnabled&&null!=appSettings.selectors.sublistButtonOpenerSelector&&(f=appSettings.selectors.sublistButtonOpenerSelector);menu_prepareTopMenu(d,f);addMobileClassIfEnabled(a.shouldAddClassForMobile);
toggleSideBlocks(b,appSettings);a.hasSideBanners&&attachDetachSideBanners(d,breakPointWidth);1==a.doesBackgroundChange&&menu_setMenuBackground(a.bgSelector,a.bgInitialColor,a.red,a.green,a.blue,a.alpha,d);1==a.doesPaddingChange&&menu_setMenuPaddings(a.paddingSelector,a.paddingValue,1,d,c);appSettings.isEnabled&&(onWidthBreak(appSettings.selectors,appSettings.isSearchBoxDetachable,appSettings.isHeaderLinksWrapperDetachable,d,b),1==appSettings.doesSublistHasIndent&&initSublistIndent(appSettings.selectors.headerMenu,
appSettings.selectors.withSubcategories))}e=d};d(!0);$.addSpikesWindowEvent("resize",function(){d(!1)});$.addSpikesWindowEvent("orientationchange",function(){d(!1)});if(appSettings.isEnabled){if(appSettings.hasStickyNav||appSettings.displayGoToTop||appSettings.doesDesktopHeaderMenuStick)null==appSettings.selectors.headerMenuDesktopStickElement&&(appSettings.selectors.headerMenuDesktopStickElement=appSettings.selectors.headerMenu),null==appSettings.selectors.headerMenuDesktopStickParentElement&&(appSettings.selectors.headerMenuDesktopStickParentElement=
"#headerMenuParent"),windowScrollEvents(appSettings.doesDesktopHeaderMenuStick,appSettings.hasStickyNav,appSettings.displayGoToTop,appSettings.selectors.navWrapper,appSettings.selectors.navWrapperParent,appSettings.selectors.headerMenuDesktopStickElement,appSettings.selectors.headerMenuDesktopStickParentElement);addDetachableClickEvents(appSettings.selectors,appSettings.isSearchBoxDetachable,appSettings.isHeaderLinksWrapperDetachable);if(1==appSettings.doesScrollAfterFiltration)$(document).on("nopAjaxFiltersFiltrationCompleteEvent",
function(){$.getSpikesViewPort().width<=breakPointWidth&&($(appSettings.selectors.overlayOffCanvas).triggerHandler("click"),setTimeout(function(){$(appSettings.selectors.overlayOffCanvas).hide()},450))})}addSideBlocksClickEvents();0==$(".nopAjaxFilters7Spikes .block").length&&$(".responsive-nav-wrapper .filters-button").remove();if(null==appSettings.DisableFootable||0==appSettings.DisableFootable)"function"==typeof $("body").footable&&$(".private-messages-page .data-table ,.order-summary-content .cart, .wishlist-page .cart, .downloadable-products-page .data-table, .return-request-page .data-table, .order-details-page .data-table, .compare-products-table-mobile, .reward-points-history .data-table").footable(),
0<$(".checkout-page").length&&$(document).ajaxSuccess(function(){0<$(".order-summary-content .cart").length&&$(".order-summary-content .cart").footable()})}
$.extend({getAttrValFromDom:function(a,b,c){a=$(a).attr(b);if(void 0==a||""==a)window.console&&window.console.log("'"+b+"' was not found."),a=void 0!=c?c:"";return a},getHiddenValFromDom:function(a,b){var c=$(a).val();if(void 0==c||""==c)c=void 0!=b?b:"";return c},getUrlVars:function(){for(var a=[],b,c=window.location.href.slice(window.location.href.indexOf("?")+1).split("&"),e=0;e<c.length;e++)b=c[e].split("="),a.push(b[0]),a[b[0]]=b[1];return a},getUrlVar:function(a){return $.getUrlVars()[a]},getSpikesViewPort:function(){var a=
window,b="inner";"innerWidth"in window||(b="client",a=document.documentElement||document.body);return{width:a[b+"Width"],height:a[b+"Height"]}},isMobile:function(){return isMobileDevice()},addSpikesWindowEvent:function(a,b){window.addEventListener?window.addEventListener(a,b,!1):window.attachEvent&&window.attachEvent("on"+a,b)}});
function attachDetachSideBanners(a,b){if(a<b){var c=$(".leftside-3 .slider-wrapper, .rightside-3 .slider-wrapper, .side-2 .slider-wrapper").detach();$(".master-wrapper-main").append('<div class="mobile-banners"></div>');$(".mobile-banners").append(c)}else $(".mobile-banners").detach()}
function menu_setMenuBackground(a,b,c,e,d,g,k){var f="rgba(",h;if(k>breakPointWidth)f="";else{try{h=b.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(0|1|0\.\d+))?\)$/),delete h[0]}catch(l){return}f=f.concat(validateColorValue(parseInt(h[1]),c)+",");f=f.concat(validateColorValue(parseInt(h[2]),e)+",");f=f.concat(validateColorValue(parseInt(h[3]),d)+",");null!=h[4]&&(h[4]=parseFloat(h[4])+g,b=parseFloat(h[4]),1<b?b=1:0>b&&(b=0),f=f.concat(b));f=f.concat(")")}$(a).css("background-color",f);a=$(a).children("li").children("ul");
0<a.length&&menu_setMenuBackground(a,f,c,e,d,g,k)}function validateColorValue(a,b){var c=parseInt(a)+b;0>c?c=0:255<c&&(c=255);return c}
function toggleSideBlocks(a,b){$(".block").each(function(){$.getSpikesViewPort().width>breakPointWidth?a||(0==b.isEnabled?($(this).children().eq(1).show(),$(this).children().eq(0).children("a.toggleControl").removeClass("closed")):$(this).children(".listbox").eq(0).show(),$(this).find(".jcarousel-container-vertical").show()):(0==b.isEnabled?($(this).children().eq(1).hide(),$(this).children().eq(0).children("a.toggleControl").addClass("closed")):$(this).children(".listbox").eq(0).hide(),$(this).find(".jcarousel-container-vertical").hide())})}
function addMobileClassIfEnabled(a){a&&$.isMobile()&&$(".product-grid .item-box").addClass("mobile-box");$(document).on("nopAjaxFiltersFiltrationCompleteEvent",function(){a&&$.isMobile()&&$(".product-grid .item-box").addClass("mobile-box")})}
function addSideBlocksClickEvents(){$(".block .title").not($(".nopAjaxFilters7Spikes .block .title")).off("click").on("click",function(){if($.getSpikesViewPort().width<=breakPointWidth){var a=$(this).siblings();a.slideToggle("slow",function(){a.css("overflow","")})}});$(".nop-jcarousel.vertical-holder .carousel-title").on("click",function(){if($.getSpikesViewPort().width<=breakPointWidth){var a=$(this).siblings();a.slideToggle("slow",function(){a.css("overflow","")})}})}
function AntiSpam(a,b){window.location.href="mailto:"+a+"@"+b}function initSublistIndent(a,b){0<$(".mega-menu-responsive").length?sublistIndent(".mega-menu-responsive > li > .sublist-wrap",b,320,1):sublistIndent(a+" > ul > li > .sublist-wrap",b,320,1)}
function menu_setMenuPaddings(a,b,c,e,d){var g=$(a).children("a, span");e<=breakPointWidth?d?(g.css("padding-left",""),g.css("padding-right",b*c)):(g.css("padding-left",b*c),g.css("padding-right","")):(g.css("padding-left",""),g.css("padding-right",""));a=$(a).children("div").children("ul").children("li");0<a.children("a").length&&menu_setMenuPaddings(a,parseInt(b),++c,e,d)}
function windowScrollEvents(a,b,c,e,d,g,k){b&&stickyNav(e,d);a&&stickyNav(g,k);$(window).on("scroll",function(){b&&stickyNav(e,d);a&&stickyNav(g,k);c&&(100<$(window).scrollTop()?$("#goToTop").show():$("#goToTop").hide());hasScrolled(e,d)});if(c)$("#goToTop").on("click",function(){$("html,body").animate({scrollTop:0},400)})}
function stickyNav(a,b){var c=$(b),e=$(window).scrollTop();0<e&&e>=c.offset().top?(c.css("height",c.height()+"px"),$(a).addClass("stick")):(c.css("height",""),$(a).removeClass("stick"))}var lastScrollTop=0;function hasScrolled(a,b){var c=$(a),e=c.filter(".stick");if(0==e.length||0==b.length)c.removeClass("nav-up");else{var d=$(window).scrollTop();d<=$(b).offset().top?c.removeClass("nav-up"):(d>lastScrollTop?e.addClass("nav-up"):e.removeClass("nav-up"),lastScrollTop=d)}}
function onWidthBreak(a,b,c,e,d){e<=breakPointWidth?($(a.headerMenu).add($(a.sublist)).add($(a.overlayOffCanvas)),$(a.filtersContainer).detach().insertAfter(a.headerMenu),b&&$(a.searchBox).detach().insertAfter(a.navWrapperParent),c&&$(a.headerLinksWrapper).detach().insertAfter(a.headerLinksWrapperMobileInsertAfter),$(a.shoppingCartLink).off("mouseenter.flyout-cart").off("mouseleave.flyout-cart"),$(".top-menu > li > .sublist-wrap").css("display","")):($(a.headerMenu).css({height:"",top:""}),$(a.sublist).css({height:"",
top:""}),$(a.filtersContainer).css("height",""),d||$(a.filtersContainer).detach().prependTo(".side-2"),c&&$(a.headerLinksWrapper).detach().prependTo(a.headerLinksWrapperDesktopPrependTo),b&&$(a.searchBox).detach().insertAfter(a.searchBoxBefore),$(a.shoppingCartLink).on("mouseenter.flyout-cart",function(a){var b=$(this).children(".flyout-cart");void 0!=b.attr("isSliding")&&"false"!=b.attr("isSliding")||b.attr("isSliding","true").slideDown(100,function(){$(this).css("overflow","");$(this).attr("isSliding",
"false")});a.preventDefault()}).on("mouseleave.flyout-cart",function(a){$(this).children(".flyout-cart").attr("isSliding","true").slideUp(100,function(){$(this).css("overflow","");$(this).attr("isSliding","false")});a.preventDefault()}))}
function menu_prepareTopMenu(a,b){if(null==appSettings||"undefined"==typeof appSettings)appSettings={isEnabled:!1};0==megaMenuSkipEventBinding&&($(".menu-title").click(function(){$(this).hasClass("close")?$(this).removeClass("close"):$(this).addClass("close");$(this).siblings(".top-menu, .mega-menu-responsive").slideToggle("fast",function(){$(this).css("overflow","")});appSettings.isEnabled&&$(".header-menu, .sublist-wrap").perfectScrollbar({swipePropagation:!1,wheelSpeed:1,suppressScrollX:!0})}),
$(b).on("click",function(a){var b=$(this);a.stopPropagation();b.hasClass("close")?b.removeClass("close"):b.addClass("close");var d=b.siblings(".sublist-wrap");d.hasClass("active")?d.removeClass("active"):appSettings.isEnabled?b.parents().eq(2).animate({scrollTop:0},180,function(){d.addClass("active")}):d.addClass("active");appSettings.isEnabled&&b.parents().eq(2).perfectScrollbar("destroy")}),megaMenuSkipEventBinding=!0);a>breakPointWidth?($(".sublist-wrap.active").removeClass("active"),$(b+".close").removeClass("close"),
$(".top-menu li").on("mouseenter",function(){$("a",$(this)).first().addClass("hover");$(".sublist-wrap",$(this)).first().addClass("active")}).on("mouseleave",function(){$("a",$(this)).first().removeClass("hover");$(".sublist-wrap",$(this)).first().removeClass("active")})):($(".top-menu li").off("mouseenter mouseleave"),$(".sublist-wrap.active").removeClass("active"),$(b+".close").removeClass("close"))}
function sublistIndent(a,b,c,e){var d=$(a);$.getSpikesViewPort().width<=breakPointWidth?(d.css({width:c-7,"z-index":d.css("z-index")+e}),$("> .sublist > li > "+b,a).css("width",c-57)):(d.css({width:"","z-index":""}),$("> .sublist > li > "+b,a).css("width",""));a+="> .sublist > li > .sublist-wrap";0<$(a).length&&sublistIndent(a,b,c-7,e+1)}
function addDetachableClickEvents(a,b,c){b&&$(".search-wrap > span").click(function(){$(a.searchBox).addClass("open");$(a.overlayOffCanvas).show(0).addClass("show");$("html, body").addClass("scrollYRemove")});$("#header-links-opener").on("click",function(){$(a.headerLinksWrapper).addClass("open");$(a.overlayOffCanvas).show(0).addClass("show");$("html, body").addClass("scrollYRemove")});$(a.menuTitle).click(function(){onMenuTitleClick(a)});$(a.closeMenu).click(function(){$(a.headerMenu).removeClass("open");
onOverlayClick(a);appSettings.isEnabled&&$(".header-menu, .sublist-wrap").perfectScrollbar("destroy")});$(a.overlayOffCanvas).click(function(){$(a.sublist).parent().removeClass("active").animate({scrollTop:0});$(a.headerMenu).add($(a.filtersContainer)).removeClass("open");b&&$(a.searchBox).removeClass("open");c&&$(a.headerLinksWrapper).removeClass("open");onOverlayClick(a);appSettings.isEnabled&&$(".header-menu, .sublist-wrap, .nopAjaxFilters7Spikes.open").perfectScrollbar("destroy")});$(".sublist").on("click",
".back-button",function(){$(this).parent(".sublist").parent(".sublist-wrap").removeClass("active");appSettings.isEnabled&&$(this).parents().eq(4).perfectScrollbar({swipePropagation:!1,wheelSpeed:2,suppressScrollX:!0})});$(a.filtersOpener).click(function(){$(a.filtersContainer).toggleClass("open");$(a.movedElements).toggleClass("move-right");$(a.overlayOffCanvas).show(0).addClass("show");$("html, body").addClass("scrollYRemove");appSettings.isEnabled&&$(".nopAjaxFilters7Spikes.open").perfectScrollbar({swipePropagation:!1,
wheelSpeed:1,suppressScrollX:!0})});$('<div class="close-filters"><span>close</span></div>').insertBefore(".filtersPanel");$(".close-filters").click(function(){$(a.filtersContainer).toggleClass("open");$(a.movedElements).toggleClass("move-right");$(a.overlayOffCanvas).removeClass("show").delay(a.overlayEffectDelay).hide(0);$("html, body").removeClass("scrollYRemove");appSettings.isEnabled&&$(".nopAjaxFilters7Spikes.open").perfectScrollbar("destroy")})}
function onMenuTitleClick(a){$(a.headerMenu).addClass("open");$(a.movedElements).addClass("move-right");$(a.overlayOffCanvas).show(0).addClass("show");$("html, body").addClass("scrollYRemove")}function onOverlayClick(a){$(a.movedElements).removeClass("move-right");$(a.overlayOffCanvas).removeClass("show").delay(a.overlayEffectDelay).hide(0);$("html, body").removeClass("scrollYRemove")}
function isMobileDevice() { var a = { Android: function () { return navigator.userAgent.match(/Android/i) }, BlackBerry: function () { return navigator.userAgent.match(/BlackBerry/i) }, iOS: function () { return navigator.userAgent.match(/iPhone|iPad|iPod/i) }, Opera: function () { return navigator.userAgent.match(/Opera Mini/i) }, Windows: function () { return navigator.userAgent.match(/IEMobile/i) }, any: function () { return a.Android() || a.BlackBerry() || a.iOS() || a.Opera() || a.Windows() } }; return a.any() };
